# PuffinZipAI_Project/puffinzip_ai/config.py
import os

LOGS_DIR_NAME = 'logs'
GENERATED_BENCHMARK_SUBDIR_NAME = 'generated_default_benchmark_subdir'
MODEL_FILENAME = 'puffin_ai_model_default.dat'

CONFIG_FILE_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT_DIR = os.path.dirname(CONFIG_FILE_DIR)
DATA_DIR = os.path.join(PROJECT_ROOT_DIR, "data")
MODELS_DIR = os.path.join(DATA_DIR, "models")
LOGS_DIR_PATH = os.path.join(PROJECT_ROOT_DIR, LOGS_DIR_NAME)
BENCHMARK_DATA_DIR = os.path.join(DATA_DIR, "benchmark_sets")
GENERATED_BENCHMARK_DEFAULT_PATH = os.path.join(BENCHMARK_DATA_DIR, GENERATED_BENCHMARK_SUBDIR_NAME)
MODEL_FILE_DEFAULT = os.path.join(MODELS_DIR, MODEL_FILENAME)

COMPRESSED_FILE_SUFFIX = '.pfz'
DEFAULT_LEN_THRESHOLDS = [50, 150, 500]
DEFAULT_BATCH_COMPRESS_EXTENSIONS = ['.txt', '.log', '.md', '.csv']
DEFAULT_ALLOWED_LEARN_EXTENSIONS = ['.txt', '.md', '.py', '.js', '.html', '.css']
CORE_AI_LOG_FILENAME = 'puffin_ai_core.log'
APP_VERSION = '0.9.5-dev' # This will be updated via changelog.md later
DEFAULT_LOG_LEVEL = 'INFO'
LOG_MAX_BYTES = 5242880 
LOG_BACKUP_COUNT = 3

DEBUG_LOG_CONSOLE_OUTPUT_ENABLED = False 

DEFAULT_LEARNING_RATE = 0.1
DEFAULT_DISCOUNT_FACTOR = 0.9
DEFAULT_EXPLORATION_RATE = 1.0
DEFAULT_EXPLORATION_DECAY_RATE = 0.9995
DEFAULT_MIN_EXPLORATION_RATE = 0.01
DEFAULT_TRAIN_BATCH_SIZE = 32
DEFAULT_FOLDER_LEARN_BATCH_SIZE = 16
DEFAULT_TRAIN_LOG_INTERVAL_BATCHES = 10

CLI_MENU_LOG_FILENAME = 'puffin_cli_menu.log'
CLI_RUNNER_LOG_FILENAME = 'puffin_cli_runner.log'
GUI_RUNNER_LOG_FILENAME = 'puffin_gui_runner_status.log'

DEFAULT_POPULATION_SIZE = 50 
DEFAULT_NUM_GENERATIONS = 100 
DEFAULT_ADDITIONAL_ELS_GENERATIONS = 30 
DEFAULT_MUTATION_RATE = 0.15 
DEFAULT_ELITISM_COUNT = 2 
DEFAULT_SELECTION_STRATEGY = 'tournament'
BENCHMARK_DATASET_PATH = None 
EVOLUTIONARY_AI_LOG_FILENAME = 'evolutionary_optimizer.log'
BENCHMARK_GENERATOR_LOG_FILENAME = 'benchmark_generator.log'

MAX_THRESHOLDS_COUNT = 7
MIN_THRESHOLDS_COUNT = 1
MAX_THRESHOLDS_COUNT_MERGED = 8
ADVANCED_CROSSOVER_PROBABILITY = 0.6 
HYPERMUTATION_THRESHOLD_COUNT_CHANGE_PROB = 0.3
HYPERMUTATION_PARAM_STRENGTH_FACTOR = 2.0
STAGNATION_GENERATIONS_THRESHOLD = 10 
MUTATION_RATE_BOOST_FACTOR = 1.8 
MUTATION_RATE_DECAY_FACTOR = 0.99
HYPERMUTATION_STAGNATION_THRESHOLD = 18 
HYPERMUTATION_FRACTION = 0.2 
RLE_MIN_RUN_INIT_MIN = 2 
RLE_MIN_RUN_INIT_MAX = 4 
RLE_MIN_RUN_MUTATION_PROB = 0.15 
RLE_MIN_RUN_BOUNDS_MIN = 2 
RLE_MIN_RUN_BOUNDS_MAX = 7 
RANDOM_IMMIGRANT_INTERVAL = 20 
RANDOM_IMMIGRANT_FRACTION = 0.1 

ELS_LOG_PREFIX = '[ELS]'
ELS_STATS_MSG_PREFIX = '[ELS_FITNESS_HISTORY]'

ACCELERATION_TARGET_DEVICE = 'GPU_ID:0' 
DYNAMIC_BENCHMARKING_ACTIVE_BY_DEFAULT = True 
DYNAMIC_BENCHMARK_REFRESH_INTERVAL_GENS = 10 
INITIAL_BENCHMARK_COMPLEXITY_LEVEL = 'SIMPLE' 

THEME_BG_COLOR = '#2E3440' #2E3440' #2E3440'
THEME_FG_COLOR = '#ECEFF4' #ECEFF4' #ECEFF4'
THEME_FRAME_BG = '#3B4252' #3B4252' #3B4252'
THEME_ACCENT_COLOR = '#88C0D0' #88C0D0' #88C0D0'
THEME_INPUT_BG = '#434C5E' #434C5E' #434C5E'
THEME_TEXT_AREA_BG = '#2E3440' #2E3440' #2E3440'
THEME_BUTTON_BG = '#4C566A' #4C566A' #4C566A'
THEME_BUTTON_FG = '#ECEFF4' #ECEFF4' #ECEFF4'
THEME_ERROR_FG = '#BF616A' #BF616A' #BF616A'

FONT_FAMILY_PRIMARY_CONFIG = 'Segoe UI' 
FONT_SIZE_BASE_CONFIG = 10 
FONT_FAMILY_MONO_CONFIG = 'Consolas' 

def ensure_dirs():
    dirs_to_create_keys = ['DATA_DIR', 'MODELS_DIR', 'LOGS_DIR_PATH', 'BENCHMARK_DATA_DIR', 'GENERATED_BENCHMARK_DEFAULT_PATH']
    for d_key in dirs_to_create_keys:
        d_path = globals().get(d_key)
        if d_path and isinstance(d_path, str) and d_path.strip():
            if not os.path.exists(d_path):
                try: os.makedirs(d_path, exist_ok=True)
                except OSError as e_dir: pass 
            elif not os.path.isdir(d_path): pass
        elif d_key == 'GENERATED_BENCHMARK_DEFAULT_PATH' and d_path is None : pass
        elif d_path is None : pass 

ensure_dirs()