# PuffinZipAI_Project/puffinzip_ai/rle_constants.py
RLE_ERROR_NO_COUNT = "ERROR_INVALID_RLE_FORMAT_NO_COUNT"
RLE_ERROR_BAD_COUNT = "ERROR_INVALID_RLE_FORMAT_BAD_COUNT"
RLE_ERROR_NO_CHAR = "ERROR_INVALID_RLE_FORMAT_NO_CHAR_AFTER_COUNT"
RLE_ERROR_MALFORMED = "ERROR_MALFORMED_RLE_STRING"
RLE_ERROR_COUNT_TOO_LARGE_FOR_SAFETY = "ERROR_COUNT_TOO_LARGE_FOR_SAFETY"
RLE_ERROR_TOTAL_SIZE_LIMIT_EXCEEDED = "ERROR_TOTAL_SIZE_LIMIT_EXCEEDED"
RLE_ERROR_MEMORY_ON_CHUNK = "ERROR_MEMORY_DURING_CHUNK_ALLOCATION"
RLE_ERROR_MEMORY_ON_JOIN = "ERROR_MEMORY_DURING_FINAL_JOIN"

RLE_DECOMPRESSION_ERRORS = {
    RLE_ERROR_NO_COUNT,
    RLE_ERROR_BAD_COUNT,
    RLE_ERROR_NO_CHAR,
    RLE_ERROR_MALFORMED,
    RLE_ERROR_COUNT_TOO_LARGE_FOR_SAFETY,
    RLE_ERROR_TOTAL_SIZE_LIMIT_EXCEEDED,
    RLE_ERROR_MEMORY_ON_CHUNK,
    RLE_ERROR_MEMORY_ON_JOIN,
}

ABSOLUTE_MAX_TOTAL_DECOMPRESSED_SIZE = 200 * 1024 * 1024
ABSOLUTE_MAX_PARSED_COUNT = 100 * 1024 * 1024
MAX_COUNT_STRING_DIGITS = 9